language: python
python:
  - '2.7'
sudo: required
services: 
  - docker
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install ansible
# Add ansible container
  - pip install ansible-container[docker]
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
before_script:
script:
- ansible-galaxy install AAROC.glibrary-role
- echo ${VAULT_PASSWORD} > vault_password
- ansible-playbook -c local tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook -c local tests/test.yml -i tests/inventory  --vault-password-file=vault_password
# build
- cd deploy/ansible-container
- 
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
env:
  global:
    secure: vIna4i1AndyOa4AUgu7qAnc7RWSHFc2hKK/tjd8OHkq3yMek64HZQqs6V1SxmgEO4vTLKh+XIOPBbJiLJx1INxiiluzD63bgaIQhsX0cUeQPhC75Ujfavt0Rs1p/z9DpQk4qijnKCUlzfADiJnq1qCYAgzxsOe+zwFPsIV8tlVWw8P0UeccSBCtNH5O6c0lGbO1H32eknqsVhESz5G7QigHzEkx8dLvA48Nk5yi7gNeZLzVdbGNx4f3EeLqpefoQken69vCueWmnGBk5vO+cdJnmg01GnGpmF+yhsUc+jjT3crJtgwIol7ai1vnA75ZSodJN9d5rOWqNDZ8D2x4w3H3OSjsd9dwNFczk6OMYHjF2z8vzYmxFxDMX4zKS0bLirBTfwKmSwgO5zebweqsrQyiOjG827+crw+4y1WW2PMfzJtnrVpvI3HSNYxw3yeaEXPJtnobvb5s6rqlGngjcwB0tDDD1xRrIwRXL3IjXiKVgWTEJgJzmabcIGllxrdbHnOuLGZWtGvNHKgiFnkW5lgYiSINUo3N4ysXqCAvL9VcjeH76THMkf+EPd3oBwPzGYHLY95spkFSboXl70kfgTOuORb/oJ577FmEJlY1/X+kQU4mUSDS41da6TNZNAIj0g46yMfLIQyrhteTL1Qmk3BSIFM6OXlPD6sDqwgdaEKs=
